name: Docker Image CI

on:  
  push:
    tags:
      - '*'
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      tag:
        description: 'tag'
        required: false
        type: string

jobs:
  build:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [ubuntu-latest]
        arch: [x64]
        
    steps:
    - uses: actions/checkout@v3
      with:
          fetch-depth: 0
    - name: check out tag
      if: ${{ inputs.tag }}
      run: git checkout tags/${{ inputs.tag }}
        
    - name: Extract branch name
      shell: bash
      run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

    - name: Build Docker Image
      run: docker build -t lucksoft/promap:${VERSION} .

    - name: Login to DockerHub
      run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

    - name: Push Docker Image
      run: docker push lucksoft/bpm-convert:${VERSION}
